# name of our workflow that will show up on github
name: NASA Project CI
# control different trigger
on:
  # push to our repo
  push:
    # this will trigger when some code is push to one of these branches
    branches: [master]
  pull_request:
    branches: [master]

# workflow is made of one or more of these jobs
jobs:
  build:
    # operation system
    runs-on: ubuntu-latest
    steps:
      # differents action that will trigger in os
      #   actions/checkout is from github and @v2 is checkout's version
      - uses: actions/checkout@v2
      - name: Use Node.js version 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm install
      - run: npm run build --prefix client

        # deploy:
  #     needs: build
